"""
Django settings for coachvirtualback project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: read secret key from environment in production
SECRET_KEY = config("SECRET_KEY", default="django-insecure-rn-ljf$%9a8^1+dsn&_^7_@5w-rajoub0h$m2q18g=glhw^blu")

# DEBUG from env (default False)
try:
    DEBUG = config("DEBUG", default=False, cast=bool)
except Exception:
    DEBUG = os.getenv("DEBUG", "false").lower() == "true"

# ALLOWED_HOSTS can be set via comma-separated env var, fallback to all for now
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*")
if isinstance(ALLOWED_HOSTS, str):
    if ALLOWED_HOSTS.strip() == "*":
        ALLOWED_HOSTS = ["*"]
    else:
        ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps de terceros
    "rest_framework",
    "corsheaders", # Asegúrate de que esté instalado: pip install django-cors-headers
    # Mis apps
    "usuarios",
    "poses",
    "suscripciones",
    "musculos",
    "dispositivo",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", # DEBE estar al principio o lo más arriba posible
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "coachvirtualback.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "coachvirtualback.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

"""Configuración de base de datos.
Se prioriza el uso de una URL completa (DATABASE_URL) si está definida en el entorno.
"""

# NOTA: Idealmente, no dejes la URL real hardcodeada aquí si subes esto a GitHub público.
database_url = config("DATABASE_URL", default="postgresql://postgres:rGuCuRzXLXRjtqTuipAFEPBMVbEhWrej@yamanote.proxy.rlwy.net:41329/railway")

if database_url:
    parsed = urlparse(database_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed.path.lstrip("/"),
            "USER": parsed.username,
            "PASSWORD": parsed.password,
            "HOST": parsed.hostname,
            "PORT": str(parsed.port) if parsed.port else "5432",
        }
    }
else:
    # Fallback a variables individuales
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="127.0.0.1"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "usuarios.Usuario"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-es"

TIME_ZONE = "America/La_Paz"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==========================================
# CONFIGURACIÓN CORS (SIN RESTRICCIONES)
# ==========================================

# Permitir solicitudes desde cualquier origen (Frontend, Postman, Mobile, etc.)
CORS_ALLOW_ALL_ORIGINS = True

# Permitir envío de cookies/headers de autorización
CORS_ALLOW_CREDENTIALS = True

# (Opcional) Si en el futuro necesitas restringir CSRF en producción (deploy HTTPS):
# CSRF_TRUSTED_ORIGINS = ["https://tudominio.com", "https://tudominio.railway.app"]