# Generated by Django 5.2.8 on 2025-12-14 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialsuscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', help_text='Estado del pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialsuscripcion',
            name='activo',
            field=models.BooleanField(default=False, help_text='Si esta suscripción está activa'),
        ),
        migrations.AddIndex(
            model_name='historialsuscripcion',
            index=models.Index(fields=['estado_pago'], name='historial_s_estado__2d3021_idx'),
        ),
    ]
