# Generated by Django 5.2.8 on 2025-12-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_historialsuscripcion_estado_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del método de pago', max_length=50, unique=True)),
                ('clave', models.CharField(help_text='Clave única (ej: stripe, qr, transferencia)', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del método')),
                ('icono', models.CharField(default='💳', help_text='Emoji o icono', max_length=10)),
                ('color', models.CharField(default='bg-blue-500', help_text='Clase CSS de color', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si el método está habilitado')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('requiere_referencia', models.BooleanField(default=False, help_text='Requiere número de referencia/transacción')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones para el usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodos_pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del plan', max_length=50, unique=True)),
                ('clave', models.CharField(help_text='Clave única del plan (ej: basico, premium)', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del plan')),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio mensual en Bs.', max_digits=10)),
                ('duracion_dias', models.IntegerField(default=30, help_text='Duración del plan en días')),
                ('minutos_por_dia', models.IntegerField(default=15, help_text='Minutos de uso por día (-1 = ilimitado)')),
                ('feedback_voz', models.BooleanField(default=False, help_text='Permite feedback con voz')),
                ('analisis_angulos', models.BooleanField(default=False, help_text='Permite análisis de ángulos')),
                ('historial_dias', models.IntegerField(default=0, help_text='Días de historial disponibles (-1 = ilimitado)')),
                ('con_anuncios', models.BooleanField(default=True, help_text='Muestra anuncios')),
                ('rutinas_personalizadas', models.BooleanField(default=False, help_text='Permite crear rutinas personalizadas')),
                ('soporte_prioritario', models.BooleanField(default=False, help_text='Acceso a soporte prioritario')),
                ('icono', models.CharField(default='⭐', help_text='Emoji o icono del plan', max_length=10)),
                ('color', models.CharField(default='from-gray-400 to-gray-500', help_text='Clase CSS de gradiente', max_length=50)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('popular', models.BooleanField(default=False, help_text='Marcar como más popular')),
                ('activo', models.BooleanField(default=True, help_text='Si el plan está disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Plan',
                'verbose_name_plural': 'Tipos de Plan',
                'db_table': 'tipos_plan',
                'ordering': ['orden', 'precio'],
            },
        ),
        migrations.AlterField(
            model_name='historialsuscripcion',
            name='metodo_pago',
            field=models.CharField(blank=True, help_text='Método de pago utilizado (legacy)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialsuscripcion',
            name='plan',
            field=models.CharField(choices=[('gratis', 'Gratis'), ('basico', 'Básico'), ('premium', 'Premium')], help_text='Plan adquirido (legacy)', max_length=20),
        ),
        migrations.AddField(
            model_name='historialsuscripcion',
            name='metodo_pago_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='suscripciones.metodopago'),
        ),
        migrations.AddField(
            model_name='historialsuscripcion',
            name='tipo_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='suscripciones.tipoplan'),
        ),
    ]
